//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18449.
// 
#pragma warning disable 1591

namespace AppProyectoDetagavos.localhostdetagavos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="detaservicioSoap", Namespace="http://detagavos.org/")]
    public partial class detaservicio : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback validarusuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback sabersiexisteusuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertarusuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback llenardgusuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarusuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarusuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertarcultivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarcultivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback eleminarcultivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback llenardgcultivosOperationCompleted;
        
        private System.Threading.SendOrPostCallback sabersiexistecultivosOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertarplagaOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarplagaOperationCompleted;
        
        private System.Threading.SendOrPostCallback eleminarplagaOperationCompleted;
        
        private System.Threading.SendOrPostCallback llenardgplagaOperationCompleted;
        
        private System.Threading.SendOrPostCallback sabersiexisteplagaOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertarsintomaOperationCompleted;
        
        private System.Threading.SendOrPostCallback actualizarsintomaOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminarsintomaOperationCompleted;
        
        private System.Threading.SendOrPostCallback llenardgsintomasOperationCompleted;
        
        private System.Threading.SendOrPostCallback LlenarcultivosOperationCompleted;
        
        private System.Threading.SendOrPostCallback algoritmodecomparacionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public detaservicio() {
            this.Url = "http://192.168.1.36:8095/detaservicio.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event validarusuariosCompletedEventHandler validarusuariosCompleted;
        
        /// <remarks/>
        public event sabersiexisteusuariosCompletedEventHandler sabersiexisteusuariosCompleted;
        
        /// <remarks/>
        public event insertarusuariosCompletedEventHandler insertarusuariosCompleted;
        
        /// <remarks/>
        public event llenardgusuariosCompletedEventHandler llenardgusuariosCompleted;
        
        /// <remarks/>
        public event actualizarusuariosCompletedEventHandler actualizarusuariosCompleted;
        
        /// <remarks/>
        public event eliminarusuariosCompletedEventHandler eliminarusuariosCompleted;
        
        /// <remarks/>
        public event insertarcultivoCompletedEventHandler insertarcultivoCompleted;
        
        /// <remarks/>
        public event actualizarcultivoCompletedEventHandler actualizarcultivoCompleted;
        
        /// <remarks/>
        public event eleminarcultivoCompletedEventHandler eleminarcultivoCompleted;
        
        /// <remarks/>
        public event llenardgcultivosCompletedEventHandler llenardgcultivosCompleted;
        
        /// <remarks/>
        public event sabersiexistecultivosCompletedEventHandler sabersiexistecultivosCompleted;
        
        /// <remarks/>
        public event insertarplagaCompletedEventHandler insertarplagaCompleted;
        
        /// <remarks/>
        public event actualizarplagaCompletedEventHandler actualizarplagaCompleted;
        
        /// <remarks/>
        public event eleminarplagaCompletedEventHandler eleminarplagaCompleted;
        
        /// <remarks/>
        public event llenardgplagaCompletedEventHandler llenardgplagaCompleted;
        
        /// <remarks/>
        public event sabersiexisteplagaCompletedEventHandler sabersiexisteplagaCompleted;
        
        /// <remarks/>
        public event insertarsintomaCompletedEventHandler insertarsintomaCompleted;
        
        /// <remarks/>
        public event actualizarsintomaCompletedEventHandler actualizarsintomaCompleted;
        
        /// <remarks/>
        public event eliminarsintomaCompletedEventHandler eliminarsintomaCompleted;
        
        /// <remarks/>
        public event llenardgsintomasCompletedEventHandler llenardgsintomasCompleted;
        
        /// <remarks/>
        public event LlenarcultivosCompletedEventHandler LlenarcultivosCompleted;
        
        /// <remarks/>
        public event algoritmodecomparacionCompletedEventHandler algoritmodecomparacionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/validarusuarios", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int validarusuarios(string usuario, string password) {
            object[] results = this.Invoke("validarusuarios", new object[] {
                        usuario,
                        password});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void validarusuariosAsync(string usuario, string password) {
            this.validarusuariosAsync(usuario, password, null);
        }
        
        /// <remarks/>
        public void validarusuariosAsync(string usuario, string password, object userState) {
            if ((this.validarusuariosOperationCompleted == null)) {
                this.validarusuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidarusuariosOperationCompleted);
            }
            this.InvokeAsync("validarusuarios", new object[] {
                        usuario,
                        password}, this.validarusuariosOperationCompleted, userState);
        }
        
        private void OnvalidarusuariosOperationCompleted(object arg) {
            if ((this.validarusuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validarusuariosCompleted(this, new validarusuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/sabersiexisteusuarios", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int sabersiexisteusuarios(string dni, string usuario) {
            object[] results = this.Invoke("sabersiexisteusuarios", new object[] {
                        dni,
                        usuario});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void sabersiexisteusuariosAsync(string dni, string usuario) {
            this.sabersiexisteusuariosAsync(dni, usuario, null);
        }
        
        /// <remarks/>
        public void sabersiexisteusuariosAsync(string dni, string usuario, object userState) {
            if ((this.sabersiexisteusuariosOperationCompleted == null)) {
                this.sabersiexisteusuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsabersiexisteusuariosOperationCompleted);
            }
            this.InvokeAsync("sabersiexisteusuarios", new object[] {
                        dni,
                        usuario}, this.sabersiexisteusuariosOperationCompleted, userState);
        }
        
        private void OnsabersiexisteusuariosOperationCompleted(object arg) {
            if ((this.sabersiexisteusuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sabersiexisteusuariosCompleted(this, new sabersiexisteusuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/insertarusuarios", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool insertarusuarios(string dni, string nombre, string apellidos, string usuario, string password) {
            object[] results = this.Invoke("insertarusuarios", new object[] {
                        dni,
                        nombre,
                        apellidos,
                        usuario,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void insertarusuariosAsync(string dni, string nombre, string apellidos, string usuario, string password) {
            this.insertarusuariosAsync(dni, nombre, apellidos, usuario, password, null);
        }
        
        /// <remarks/>
        public void insertarusuariosAsync(string dni, string nombre, string apellidos, string usuario, string password, object userState) {
            if ((this.insertarusuariosOperationCompleted == null)) {
                this.insertarusuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertarusuariosOperationCompleted);
            }
            this.InvokeAsync("insertarusuarios", new object[] {
                        dni,
                        nombre,
                        apellidos,
                        usuario,
                        password}, this.insertarusuariosOperationCompleted, userState);
        }
        
        private void OninsertarusuariosOperationCompleted(object arg) {
            if ((this.insertarusuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertarusuariosCompleted(this, new insertarusuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/llenardgusuarios", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet llenardgusuarios(string nombre) {
            object[] results = this.Invoke("llenardgusuarios", new object[] {
                        nombre});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void llenardgusuariosAsync(string nombre) {
            this.llenardgusuariosAsync(nombre, null);
        }
        
        /// <remarks/>
        public void llenardgusuariosAsync(string nombre, object userState) {
            if ((this.llenardgusuariosOperationCompleted == null)) {
                this.llenardgusuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnllenardgusuariosOperationCompleted);
            }
            this.InvokeAsync("llenardgusuarios", new object[] {
                        nombre}, this.llenardgusuariosOperationCompleted, userState);
        }
        
        private void OnllenardgusuariosOperationCompleted(object arg) {
            if ((this.llenardgusuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.llenardgusuariosCompleted(this, new llenardgusuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/actualizarusuarios", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool actualizarusuarios(string dni, string nombre, string apellidos, string usuario, string password) {
            object[] results = this.Invoke("actualizarusuarios", new object[] {
                        dni,
                        nombre,
                        apellidos,
                        usuario,
                        password});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarusuariosAsync(string dni, string nombre, string apellidos, string usuario, string password) {
            this.actualizarusuariosAsync(dni, nombre, apellidos, usuario, password, null);
        }
        
        /// <remarks/>
        public void actualizarusuariosAsync(string dni, string nombre, string apellidos, string usuario, string password, object userState) {
            if ((this.actualizarusuariosOperationCompleted == null)) {
                this.actualizarusuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarusuariosOperationCompleted);
            }
            this.InvokeAsync("actualizarusuarios", new object[] {
                        dni,
                        nombre,
                        apellidos,
                        usuario,
                        password}, this.actualizarusuariosOperationCompleted, userState);
        }
        
        private void OnactualizarusuariosOperationCompleted(object arg) {
            if ((this.actualizarusuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarusuariosCompleted(this, new actualizarusuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/eliminarusuarios", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool eliminarusuarios(string dni, string usuario) {
            object[] results = this.Invoke("eliminarusuarios", new object[] {
                        dni,
                        usuario});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarusuariosAsync(string dni, string usuario) {
            this.eliminarusuariosAsync(dni, usuario, null);
        }
        
        /// <remarks/>
        public void eliminarusuariosAsync(string dni, string usuario, object userState) {
            if ((this.eliminarusuariosOperationCompleted == null)) {
                this.eliminarusuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarusuariosOperationCompleted);
            }
            this.InvokeAsync("eliminarusuarios", new object[] {
                        dni,
                        usuario}, this.eliminarusuariosOperationCompleted, userState);
        }
        
        private void OneliminarusuariosOperationCompleted(object arg) {
            if ((this.eliminarusuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarusuariosCompleted(this, new eliminarusuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/insertarcultivo", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool insertarcultivo(string nombre) {
            object[] results = this.Invoke("insertarcultivo", new object[] {
                        nombre});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void insertarcultivoAsync(string nombre) {
            this.insertarcultivoAsync(nombre, null);
        }
        
        /// <remarks/>
        public void insertarcultivoAsync(string nombre, object userState) {
            if ((this.insertarcultivoOperationCompleted == null)) {
                this.insertarcultivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertarcultivoOperationCompleted);
            }
            this.InvokeAsync("insertarcultivo", new object[] {
                        nombre}, this.insertarcultivoOperationCompleted, userState);
        }
        
        private void OninsertarcultivoOperationCompleted(object arg) {
            if ((this.insertarcultivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertarcultivoCompleted(this, new insertarcultivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/actualizarcultivo", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool actualizarcultivo(string nombrenuevo, string id) {
            object[] results = this.Invoke("actualizarcultivo", new object[] {
                        nombrenuevo,
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarcultivoAsync(string nombrenuevo, string id) {
            this.actualizarcultivoAsync(nombrenuevo, id, null);
        }
        
        /// <remarks/>
        public void actualizarcultivoAsync(string nombrenuevo, string id, object userState) {
            if ((this.actualizarcultivoOperationCompleted == null)) {
                this.actualizarcultivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarcultivoOperationCompleted);
            }
            this.InvokeAsync("actualizarcultivo", new object[] {
                        nombrenuevo,
                        id}, this.actualizarcultivoOperationCompleted, userState);
        }
        
        private void OnactualizarcultivoOperationCompleted(object arg) {
            if ((this.actualizarcultivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarcultivoCompleted(this, new actualizarcultivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/eleminarcultivo", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool eleminarcultivo(string id) {
            object[] results = this.Invoke("eleminarcultivo", new object[] {
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eleminarcultivoAsync(string id) {
            this.eleminarcultivoAsync(id, null);
        }
        
        /// <remarks/>
        public void eleminarcultivoAsync(string id, object userState) {
            if ((this.eleminarcultivoOperationCompleted == null)) {
                this.eleminarcultivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OneleminarcultivoOperationCompleted);
            }
            this.InvokeAsync("eleminarcultivo", new object[] {
                        id}, this.eleminarcultivoOperationCompleted, userState);
        }
        
        private void OneleminarcultivoOperationCompleted(object arg) {
            if ((this.eleminarcultivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eleminarcultivoCompleted(this, new eleminarcultivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/llenardgcultivos", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet llenardgcultivos(string nombre) {
            object[] results = this.Invoke("llenardgcultivos", new object[] {
                        nombre});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void llenardgcultivosAsync(string nombre) {
            this.llenardgcultivosAsync(nombre, null);
        }
        
        /// <remarks/>
        public void llenardgcultivosAsync(string nombre, object userState) {
            if ((this.llenardgcultivosOperationCompleted == null)) {
                this.llenardgcultivosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnllenardgcultivosOperationCompleted);
            }
            this.InvokeAsync("llenardgcultivos", new object[] {
                        nombre}, this.llenardgcultivosOperationCompleted, userState);
        }
        
        private void OnllenardgcultivosOperationCompleted(object arg) {
            if ((this.llenardgcultivosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.llenardgcultivosCompleted(this, new llenardgcultivosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/sabersiexistecultivos", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int sabersiexistecultivos(string nombre) {
            object[] results = this.Invoke("sabersiexistecultivos", new object[] {
                        nombre});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void sabersiexistecultivosAsync(string nombre) {
            this.sabersiexistecultivosAsync(nombre, null);
        }
        
        /// <remarks/>
        public void sabersiexistecultivosAsync(string nombre, object userState) {
            if ((this.sabersiexistecultivosOperationCompleted == null)) {
                this.sabersiexistecultivosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsabersiexistecultivosOperationCompleted);
            }
            this.InvokeAsync("sabersiexistecultivos", new object[] {
                        nombre}, this.sabersiexistecultivosOperationCompleted, userState);
        }
        
        private void OnsabersiexistecultivosOperationCompleted(object arg) {
            if ((this.sabersiexistecultivosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sabersiexistecultivosCompleted(this, new sabersiexistecultivosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/insertarplaga", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool insertarplaga(string nombre, string cultivo, string cura) {
            object[] results = this.Invoke("insertarplaga", new object[] {
                        nombre,
                        cultivo,
                        cura});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void insertarplagaAsync(string nombre, string cultivo, string cura) {
            this.insertarplagaAsync(nombre, cultivo, cura, null);
        }
        
        /// <remarks/>
        public void insertarplagaAsync(string nombre, string cultivo, string cura, object userState) {
            if ((this.insertarplagaOperationCompleted == null)) {
                this.insertarplagaOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertarplagaOperationCompleted);
            }
            this.InvokeAsync("insertarplaga", new object[] {
                        nombre,
                        cultivo,
                        cura}, this.insertarplagaOperationCompleted, userState);
        }
        
        private void OninsertarplagaOperationCompleted(object arg) {
            if ((this.insertarplagaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertarplagaCompleted(this, new insertarplagaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/actualizarplaga", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool actualizarplaga(string nombrenuevo, string id, string cultivo, string cura) {
            object[] results = this.Invoke("actualizarplaga", new object[] {
                        nombrenuevo,
                        id,
                        cultivo,
                        cura});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarplagaAsync(string nombrenuevo, string id, string cultivo, string cura) {
            this.actualizarplagaAsync(nombrenuevo, id, cultivo, cura, null);
        }
        
        /// <remarks/>
        public void actualizarplagaAsync(string nombrenuevo, string id, string cultivo, string cura, object userState) {
            if ((this.actualizarplagaOperationCompleted == null)) {
                this.actualizarplagaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarplagaOperationCompleted);
            }
            this.InvokeAsync("actualizarplaga", new object[] {
                        nombrenuevo,
                        id,
                        cultivo,
                        cura}, this.actualizarplagaOperationCompleted, userState);
        }
        
        private void OnactualizarplagaOperationCompleted(object arg) {
            if ((this.actualizarplagaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarplagaCompleted(this, new actualizarplagaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/eleminarplaga", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool eleminarplaga(string id) {
            object[] results = this.Invoke("eleminarplaga", new object[] {
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eleminarplagaAsync(string id) {
            this.eleminarplagaAsync(id, null);
        }
        
        /// <remarks/>
        public void eleminarplagaAsync(string id, object userState) {
            if ((this.eleminarplagaOperationCompleted == null)) {
                this.eleminarplagaOperationCompleted = new System.Threading.SendOrPostCallback(this.OneleminarplagaOperationCompleted);
            }
            this.InvokeAsync("eleminarplaga", new object[] {
                        id}, this.eleminarplagaOperationCompleted, userState);
        }
        
        private void OneleminarplagaOperationCompleted(object arg) {
            if ((this.eleminarplagaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eleminarplagaCompleted(this, new eleminarplagaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/llenardgplaga", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet llenardgplaga(string nombre, string cultivo) {
            object[] results = this.Invoke("llenardgplaga", new object[] {
                        nombre,
                        cultivo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void llenardgplagaAsync(string nombre, string cultivo) {
            this.llenardgplagaAsync(nombre, cultivo, null);
        }
        
        /// <remarks/>
        public void llenardgplagaAsync(string nombre, string cultivo, object userState) {
            if ((this.llenardgplagaOperationCompleted == null)) {
                this.llenardgplagaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnllenardgplagaOperationCompleted);
            }
            this.InvokeAsync("llenardgplaga", new object[] {
                        nombre,
                        cultivo}, this.llenardgplagaOperationCompleted, userState);
        }
        
        private void OnllenardgplagaOperationCompleted(object arg) {
            if ((this.llenardgplagaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.llenardgplagaCompleted(this, new llenardgplagaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/sabersiexisteplaga", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int sabersiexisteplaga(string nombre, string cultivo) {
            object[] results = this.Invoke("sabersiexisteplaga", new object[] {
                        nombre,
                        cultivo});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void sabersiexisteplagaAsync(string nombre, string cultivo) {
            this.sabersiexisteplagaAsync(nombre, cultivo, null);
        }
        
        /// <remarks/>
        public void sabersiexisteplagaAsync(string nombre, string cultivo, object userState) {
            if ((this.sabersiexisteplagaOperationCompleted == null)) {
                this.sabersiexisteplagaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsabersiexisteplagaOperationCompleted);
            }
            this.InvokeAsync("sabersiexisteplaga", new object[] {
                        nombre,
                        cultivo}, this.sabersiexisteplagaOperationCompleted, userState);
        }
        
        private void OnsabersiexisteplagaOperationCompleted(object arg) {
            if ((this.sabersiexisteplagaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sabersiexisteplagaCompleted(this, new sabersiexisteplagaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/insertarsintoma", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool insertarsintoma(string nombre, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] imagen, string plaga) {
            object[] results = this.Invoke("insertarsintoma", new object[] {
                        nombre,
                        imagen,
                        plaga});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void insertarsintomaAsync(string nombre, byte[] imagen, string plaga) {
            this.insertarsintomaAsync(nombre, imagen, plaga, null);
        }
        
        /// <remarks/>
        public void insertarsintomaAsync(string nombre, byte[] imagen, string plaga, object userState) {
            if ((this.insertarsintomaOperationCompleted == null)) {
                this.insertarsintomaOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertarsintomaOperationCompleted);
            }
            this.InvokeAsync("insertarsintoma", new object[] {
                        nombre,
                        imagen,
                        plaga}, this.insertarsintomaOperationCompleted, userState);
        }
        
        private void OninsertarsintomaOperationCompleted(object arg) {
            if ((this.insertarsintomaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertarsintomaCompleted(this, new insertarsintomaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/actualizarsintoma", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool actualizarsintoma(string id, string nombre, string plaga) {
            object[] results = this.Invoke("actualizarsintoma", new object[] {
                        id,
                        nombre,
                        plaga});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void actualizarsintomaAsync(string id, string nombre, string plaga) {
            this.actualizarsintomaAsync(id, nombre, plaga, null);
        }
        
        /// <remarks/>
        public void actualizarsintomaAsync(string id, string nombre, string plaga, object userState) {
            if ((this.actualizarsintomaOperationCompleted == null)) {
                this.actualizarsintomaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnactualizarsintomaOperationCompleted);
            }
            this.InvokeAsync("actualizarsintoma", new object[] {
                        id,
                        nombre,
                        plaga}, this.actualizarsintomaOperationCompleted, userState);
        }
        
        private void OnactualizarsintomaOperationCompleted(object arg) {
            if ((this.actualizarsintomaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.actualizarsintomaCompleted(this, new actualizarsintomaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/eliminarsintoma", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool eliminarsintoma(string id) {
            object[] results = this.Invoke("eliminarsintoma", new object[] {
                        id});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void eliminarsintomaAsync(string id) {
            this.eliminarsintomaAsync(id, null);
        }
        
        /// <remarks/>
        public void eliminarsintomaAsync(string id, object userState) {
            if ((this.eliminarsintomaOperationCompleted == null)) {
                this.eliminarsintomaOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminarsintomaOperationCompleted);
            }
            this.InvokeAsync("eliminarsintoma", new object[] {
                        id}, this.eliminarsintomaOperationCompleted, userState);
        }
        
        private void OneliminarsintomaOperationCompleted(object arg) {
            if ((this.eliminarsintomaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminarsintomaCompleted(this, new eliminarsintomaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/llenardgsintomas", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet llenardgsintomas(string nombre, string plaga) {
            object[] results = this.Invoke("llenardgsintomas", new object[] {
                        nombre,
                        plaga});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void llenardgsintomasAsync(string nombre, string plaga) {
            this.llenardgsintomasAsync(nombre, plaga, null);
        }
        
        /// <remarks/>
        public void llenardgsintomasAsync(string nombre, string plaga, object userState) {
            if ((this.llenardgsintomasOperationCompleted == null)) {
                this.llenardgsintomasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnllenardgsintomasOperationCompleted);
            }
            this.InvokeAsync("llenardgsintomas", new object[] {
                        nombre,
                        plaga}, this.llenardgsintomasOperationCompleted, userState);
        }
        
        private void OnllenardgsintomasOperationCompleted(object arg) {
            if ((this.llenardgsintomasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.llenardgsintomasCompleted(this, new llenardgsintomasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/Llenarcultivos", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Llenarcultivos() {
            object[] results = this.Invoke("Llenarcultivos", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void LlenarcultivosAsync() {
            this.LlenarcultivosAsync(null);
        }
        
        /// <remarks/>
        public void LlenarcultivosAsync(object userState) {
            if ((this.LlenarcultivosOperationCompleted == null)) {
                this.LlenarcultivosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLlenarcultivosOperationCompleted);
            }
            this.InvokeAsync("Llenarcultivos", new object[0], this.LlenarcultivosOperationCompleted, userState);
        }
        
        private void OnLlenarcultivosOperationCompleted(object arg) {
            if ((this.LlenarcultivosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LlenarcultivosCompleted(this, new LlenarcultivosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://detagavos.org/algoritmodecomparacion", RequestNamespace="http://detagavos.org/", ResponseNamespace="http://detagavos.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string algoritmodecomparacion([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] imagen, string cultivo) {
            object[] results = this.Invoke("algoritmodecomparacion", new object[] {
                        imagen,
                        cultivo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void algoritmodecomparacionAsync(byte[] imagen, string cultivo) {
            this.algoritmodecomparacionAsync(imagen, cultivo, null);
        }
        
        /// <remarks/>
        public void algoritmodecomparacionAsync(byte[] imagen, string cultivo, object userState) {
            if ((this.algoritmodecomparacionOperationCompleted == null)) {
                this.algoritmodecomparacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnalgoritmodecomparacionOperationCompleted);
            }
            this.InvokeAsync("algoritmodecomparacion", new object[] {
                        imagen,
                        cultivo}, this.algoritmodecomparacionOperationCompleted, userState);
        }
        
        private void OnalgoritmodecomparacionOperationCompleted(object arg) {
            if ((this.algoritmodecomparacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.algoritmodecomparacionCompleted(this, new algoritmodecomparacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void validarusuariosCompletedEventHandler(object sender, validarusuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validarusuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validarusuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void sabersiexisteusuariosCompletedEventHandler(object sender, sabersiexisteusuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sabersiexisteusuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sabersiexisteusuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void insertarusuariosCompletedEventHandler(object sender, insertarusuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertarusuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertarusuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void llenardgusuariosCompletedEventHandler(object sender, llenardgusuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class llenardgusuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal llenardgusuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void actualizarusuariosCompletedEventHandler(object sender, actualizarusuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarusuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarusuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void eliminarusuariosCompletedEventHandler(object sender, eliminarusuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarusuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarusuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void insertarcultivoCompletedEventHandler(object sender, insertarcultivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertarcultivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertarcultivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void actualizarcultivoCompletedEventHandler(object sender, actualizarcultivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarcultivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarcultivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void eleminarcultivoCompletedEventHandler(object sender, eleminarcultivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eleminarcultivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eleminarcultivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void llenardgcultivosCompletedEventHandler(object sender, llenardgcultivosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class llenardgcultivosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal llenardgcultivosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void sabersiexistecultivosCompletedEventHandler(object sender, sabersiexistecultivosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sabersiexistecultivosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sabersiexistecultivosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void insertarplagaCompletedEventHandler(object sender, insertarplagaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertarplagaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertarplagaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void actualizarplagaCompletedEventHandler(object sender, actualizarplagaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarplagaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarplagaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void eleminarplagaCompletedEventHandler(object sender, eleminarplagaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eleminarplagaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eleminarplagaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void llenardgplagaCompletedEventHandler(object sender, llenardgplagaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class llenardgplagaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal llenardgplagaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void sabersiexisteplagaCompletedEventHandler(object sender, sabersiexisteplagaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sabersiexisteplagaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sabersiexisteplagaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void insertarsintomaCompletedEventHandler(object sender, insertarsintomaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class insertarsintomaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal insertarsintomaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void actualizarsintomaCompletedEventHandler(object sender, actualizarsintomaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class actualizarsintomaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal actualizarsintomaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void eliminarsintomaCompletedEventHandler(object sender, eliminarsintomaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminarsintomaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminarsintomaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void llenardgsintomasCompletedEventHandler(object sender, llenardgsintomasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class llenardgsintomasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal llenardgsintomasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void LlenarcultivosCompletedEventHandler(object sender, LlenarcultivosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LlenarcultivosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LlenarcultivosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void algoritmodecomparacionCompletedEventHandler(object sender, algoritmodecomparacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class algoritmodecomparacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal algoritmodecomparacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591